### ISSUE TITLE
Please comment here to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/awesome-june-class#1]
Say anything

**Comment by maru-villanueva** [comment]
Exciting to be in class

**Comment by alecaldapa** [comment]
Thank you

**Comment by kdp19742** [comment]
Hello

**Comment by loupendley** [comment]
Howdy!

**Comment by jzhu8** [comment]
Hi

**Comment by rjschad** [comment]
Rio is here

**Comment by anuragkum** [comment]
Hello!

**Comment by ernipun1** [comment]
Howdy!!!

**Comment by gh180005** [comment]
anything

**Comment by SUK109** [comment]
Hello

**Comment by rs186002** [comment]
rs186002

**Comment by wdzfortune** [comment]
Please add me. dazhi.wang@teradata.com

**Comment by hollenberry** [comment]
👋

**Comment by tl151006** [comment]
Hi

**Comment by saravanankaliyamoorthi** [comment]
Please add me as a collaborator...

**Comment by brandondinh** [comment]
add me

**Comment by heenamore** [comment]
Add heena.more as collaborator

**Comment by githubteacher** [comment]
:tada: @maru-villanueva, @alecaldapa, @kdp19742, @lp110118, @jzhu8, @rjschad, @anuragkum, @ernipun1, @gh180005, @SUK109, @rs186002, @wdzfortune, @hollenberry, @tl151006, @saravanankaliyamoorthi, @brandondinh, and @heenamore are now  repository collaborators. :balloon:

**Comment by yaning98** [comment]
My first comment

**Comment by githubteacher** [comment]
:tada: @yaning98 is now a repository collaborator. :balloon:

**Comment by yi200001** [comment]
My first comment too

**Comment by githubteacher** [comment]
:tada: @yi200001 is now a repository collaborator. :balloon:

**Comment by taksd** [comment]
Hello, this is Tak

**Comment by alecaldapa** [comment]
@githubteacher
